title: ""
description: ""


baseurl: "/compile-graph-break-site/docs"

theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

exclude:
  - generate-site.py
  - README.md
  - .gitignore
  - .github
