export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function GBLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="gb-layout-wrapper">
      {children}
    </div>
  );
}
